from __future__ import annotations
from collections import Counter
from typing import Any, Mapping
from ulga.builders import build_a1fs_v1_u02qb02_unit02_plain_s_questionbank_candidate_pool as u02qb02
from ulga.builders import build_a1fs_v1_u02ch01_unit02_native_chunk_assets as u02ch01
from .constants import *
from .engine import digest, normalize_surface


def build_payload(production: Mapping[str, Any]) -> dict[str, Any]:
    universe=production["universe"]; generated=production["generated"]; admitted=production["admitted"]; rejected=production["rejected"]; deferred=production["deferred"]
    target_surfaces={normalize_surface(x["surface"]) for x in universe["targets"]}
    bindable_targets={normalize_surface(x["singular"]) for x in admitted if x["generation_role"]=="MORPHOLOGY_TARGET"}
    pattern_generated=Counter(x["pattern_id"] for x in generated); pattern_admitted=Counter(x["pattern_id"] for x in admitted); pattern_rejected=Counter(x["pattern_id"] for x in rejected); pattern_deferred=Counter(x["pattern_id"] for x in deferred)
    q2_list=[]
    for row in sorted(universe["targets"], key=lambda x: normalize_surface(x["surface"])):
        restricted=normalize_surface(row["surface"]) in CHILD_CONTEXT_RESTRICTED_MORPHOLOGY_TARGETS
        q2_list.append({"singular":row["surface"],"plural":row["plural"],"vocabulary_ids":list(row["vocabulary_ids"]),"morphology_class":"PLAIN_S_AUTHORITY","unit02_target":True,"yle_bands":list(row.get("yle_bands",[])),"sentence_bindable":not restricted,"sentence_binding_disposition":"CHILD_CONTEXT_RESTRICTED" if restricted else "BINDABLE"})
    cumulative=EXPECTED_UNIT01_SENTENCE_ASSETS+len(admitted)
    return {
        "schema_version":SCHEMA_VERSION,"program_id":PROGRAM_ID,"task_id":TASK_ID,"status":PASS_STATUS,
        "source_authority":{"unit01_sentence_pool_drive_file_id":"1U4J1BZ0byM0mVLpLU0CoFrVNr28vsc55","unit01_sentence_pool_sha256":UNIT01_SENTENCE_POOL_SHA256,"unit01_defer_drive_file_id":"1F758EoI5g_6jTwqfDvMIUZZw9YamzMuJ","unit01_defer_sha256":UNIT01_DEFER_SHA256,"cambridge_yle_drive_file_id":"1O9NrRY-IrXNPBoSnc5narXttkTRyGaGL","cambridge_yle_sha256":CAMBRIDGE_YLE_SHA256,"cambridge_yle_role":"LEXICAL_EXPANSION_EVIDENCE_ONLY","canonical_vocabulary_path":"vocabulary/json/vocabulary.json","canonical_vocabulary_git_blob_sha":VOCABULARY_GIT_BLOB_SHA,"u02qb01_task_id":u02qb02.load_inventory()["task_id"],"u02ch01_task_id":u02ch01.TASK_ID,"u02sp02_task_id":production["q5"]["task_id"]},
        "pipeline_counts":{"unit01_base_sentence_assets":EXPECTED_UNIT01_SENTENCE_ASSETS,"unit01_exact_text_identities":EXPECTED_UNIT01_EXACT_TEXT_IDENTITIES,"unit01_normalized_text_identities":EXPECTED_UNIT01_NORMALIZED_TEXT_IDENTITIES,"unit02_morphology_target_nouns":len(universe["targets"]),"yle_mapping_relationships":universe["yle_mapping_relationship_count"],"yle_unmapped_noun_evidence_rows":universe["yle_unmapped_evidence_count"],"yle_a1_plain_s_lexical_expansion_nouns":len(universe["expansion_valid"]),"unit01_cumulative_reuse_lexical_nouns":len(universe["u01_reuse_valid"]),"yle_structural_reject_nouns":len(universe["expansion_structural_rejects"]),"q2_non_plain_s_exclusion_surface_count":universe["q2_non_plain_s_exclusion_surface_count"],"yle_a2_locked_mapped_vocab_ids":len(universe["yle_a2_locked_mapped_vocab_ids"]),"unit02_np_inventory":len(production["np_inventory"]),"unit02_generated_sentence_candidates":len(generated),"unit02_cumulative_exact_or_normalized_reuse":0,"unit02_semantic_review_eligible":len(generated),"unit02_semantic_approved":len(admitted),"unit02_semantic_rejected":len(rejected),"unit02_semantic_deferred":len(deferred),"unit02_new_admitted":len(admitted),"unit02_sentence_bindable_morphology_target_nouns":len(bindable_targets),"unit02_child_context_restricted_morphology_target_nouns":len(target_surfaces-bindable_targets),"cumulative_distinct_sentence_assets":cumulative},
        "q2_vocabulary_morphology_list":q2_list,
        "pattern_counts":{pid:{"generated":pattern_generated[pid],"admitted":pattern_admitted[pid],"rejected":pattern_rejected[pid],"deferred":pattern_deferred[pid]} for pid in PATTERN_TEMPLATES},
        "morphology_gate":{"q2_non_plain_s_exclusion_surface_count":universe["q2_non_plain_s_exclusion_surface_count"],"q2_non_plain_s_exclusion_family_counts":dict(universe["q2_non_plain_s_exclusion_family_counts"]),"structural_reject_reason_counts":dict(Counter(x["structural_reason"] for x in universe["expansion_structural_rejects"])),"q2_non_plain_s_authority_reused":True,"lexical_expansion_cannot_override_q2_morphology_exclusion":True},
        "private_cumulative_dedup_receipt":dict(production["dedup_receipt"]),
        "semantic_pedagogical_admission":{"review_stage":"POST_GENERATION_FULL_SENTENCE_REVIEW","deterministic_replay":True,"rejection_memory_preserved":True,"defer_memory_preserved":True,"rejected_count":len(rejected),"deferred_count":len(deferred),"rejection_memory_digest":digest(rejected),"defer_memory_digest":digest(deferred)},
        "sentence_binding_safety_exception":{"morphology_target_denominator":len(target_surfaces),"sentence_bindable_target_count":len(bindable_targets),"restricted_target_surfaces":sorted(target_surfaces-bindable_targets),"disposition":"MORPHOLOGY_TARGET_RETAINED_BUT_LEARNER_SENTENCE_ASSET_WITHHELD","q2_authority_mutated":False,"qbc02_mutated":False,"downstream_reconciliation_required":True},
        "legacy_unit02_reconciliation":{"legacy_qbc02_approved_item_count":u02qb02.EXPECTED_APPROVED,"legacy_qbc02_disposition":"REUSE_WITH_DOWNSTREAM_CHILD_CONTEXT_FILTER_RECONCILIATION","legacy_qbc02_child_context_reconciliation_required":True,"legacy_qbc02_child_context_restricted_surfaces":["beer"],"unit02_native_chunk_count":EXPECTED_U02_NATIVE_CHUNKS,"old_u02sa01_read_only_3805_984_4_model":"SUPERSEDED_BY_R1_DYNAMIC_PRODUCTION_PIPELINE","legacy_asset_delete_count":0,"second_unit02_authority_created":False},
        "identity_contract":{"unit01_identity_count_preserved":True,"exact_and_normalized_dedup_against_unit01_completed":True,"generated_candidate_is_not_sentence_asset":True,"semantic_reject_is_not_sentence_asset":True,"semantic_defer_is_not_sentence_asset":True,"only_semantic_approve_creates_u02_sentence_asset":True,"cumulative_formula":"3805 + UNIT02_NEW_ADMITTED","unit02_is_delta_over_existing_cumulative_authority":True},
        "sentence_asset_delta":{"asset_count":len(admitted),"asset_digest":digest(admitted),"assets":admitted},
        "coverage_verdict":{"q6_production_pipeline_materialized":True,"unit02_sentence_asset_admission_closeout_complete":True,"unrestricted_162_of_162_sentence_binding_claimed":False,"unit02_new_admitted_is_dynamic_current_authority_production_count":True,"old_minimum_4_witness_model_superseded":True,"cumulative_sentence_asset_coverage_closed_with_explicit_safe_exception":True,"all_sentence_bindable_morphology_targets_covered":bindable_targets==target_surfaces-set(CHILD_CONTEXT_RESTRICTED_MORPHOLOGY_TARGETS),"a2_curriculum_unlocked":False,"questionbank_mutated":False,"runtime_connected":False},
        "claim_boundaries":{"canonical_vocabulary_mutated":False,"cambridge_yle_promoted_to_vocabulary_authority":False,"unit01_sentence_assets_mutated":False,"unit02_legacy_assets_deleted":False,"second_unit02_authority_created":False,"sentence_pattern_authority_mutated":False,"chunk_authority_mutated":False,"questionbank_mutated":False,"runtime_connected":False,"learner_state_mutated":False,"a2_unlocked":False},
        "next_short_step":NEXT_SHORT_STEP,
    }
