'use strict';
let state=null,currentUnit=null,currentLane=null,active=null,pendingResume=null;
const status=document.querySelector('#status'),units=document.querySelector('#units'),lanes=document.querySelector('#lanes'),items=document.querySelector('#items'),complete=document.querySelector('#complete'),refresh=document.querySelector('#refresh-progress'),activePanel=document.querySelector('#active-panel'),activeLabel=document.querySelector('#active-label'),resume=document.querySelector('#resume'),abandon=document.querySelector('#abandon'),laneNote=document.querySelector('#lane-note'),progressSummary=document.querySelector('#progress-summary'),progressSkills=document.querySelector('#progress-skills'),progressUnits=document.querySelector('#progress-units'),progressDebug=document.querySelector('#progress-debug'),gatePanel=document.querySelector('#completion-gate'),gateSummary=document.querySelector('#gate-summary'),gateItems=document.querySelector('#gate-items'),canonicalSummary=document.querySelector('#canonical-summary'),canonicalState=document.querySelector('#canonical-state');
const text=(node,value)=>{node.textContent=value??''};const locked=()=>Boolean(active||pendingResume);
const sessionStateLabel=value=>({ACTIVE:'本次學習進行中',COMPLETED:'本次學習已完成（SESSION_COMPLETED）',ABANDONED:'本次學習已放棄'}[value]||value||'');
const activityLabel=value=>({NOT_STARTED:'尚未開始',SESSION_IN_PROGRESS:'本次學習進行中',SESSION_ACTIVITY_RECORDED:'已有學習活動',DEFERRED:'暫緩'}[value]||value||'');
const outcomeLabel=value=>({AUTO_PASS:'作答正確',AUTO_FAIL:'需要再練習',PENDING_HUMAN_REVIEW:'等待人工審核',HUMAN_APPROVE:'人工審核通過',HUMAN_REJECT:'人工審核未通過',HUMAN_DEFER:'人工審核暫緩',RECORDED:'練習已記錄'}[value]||value||'');
async function api(path,body){const hasBody=body!==undefined;const response=await fetch(path,{method:hasBody?'POST':'GET',headers:hasBody?{'Content-Type':'application/json'}:{},body:hasBody?JSON.stringify(body):undefined});const value=await response.json();if(!response.ok)throw new Error(value.error||'request_failed');return value}
function metric(label,value){const node=document.createElement('div');node.className='metric';const strong=document.createElement('strong');text(strong,value);const span=document.createElement('span');text(span,label);node.append(strong,span);return node}
function progressCard(title,statusValue,lines=[]){const node=document.createElement('article');node.className='progress-card';const heading=document.createElement('h4');text(heading,title);const badge=document.createElement('span');badge.className='badge';text(badge,activityLabel(statusValue));node.append(heading,badge);for(const line of lines){const paragraph=document.createElement('p');text(paragraph,line);node.append(paragraph)}return node}
function gateStateLabel(value){return({NOT_ATTEMPTED:'尚未作答',PASSED:'已通過',RETRY_REQUIRED:'請再作答',PENDING_HUMAN_REVIEW:'等待人工審核'}[value]||value||'')}function renderGate(gate){gateItems.replaceChildren();if(!active||!gate){gatePanel.hidden=true;complete.disabled=true;return}gatePanel.hidden=false;if(gate.skill==='SPEAKING'){text(gateSummary,'口說是練習模式，不錄音、不評分。');complete.disabled=false;return}text(gateSummary,gate.completion_allowed?'全部最新作答已通過，可以完成本次學習。':`已通過 ${gate.passed_response_count}／${gate.required_response_count}；請完成其餘項目。`);for(const row of gate.assets){const card=document.createElement('article');card.className='gate-item '+(row.completion_state==='PASSED'?'gate-ready':'gate-blocked');const title=document.createElement('strong');text(title,`第 ${row.asset_index} 題`);const stateNode=document.createElement('p');text(stateNode,gateStateLabel(row.completion_state));const attempts=document.createElement('p');attempts.className='attempt-note';text(attempts,`作答次數：${row.attempt_count}${row.latest_outcome?'；最新：'+outcomeLabel(row.latest_outcome):''}`);card.append(title,stateNode,attempts);gateItems.append(card)}complete.disabled=!gate.completion_allowed}function renderCanonical(value){canonicalSummary.replaceChildren();const state=value||{};canonicalSummary.append(metric('已精熟節點',state.mastered_required_count||0),metric('待補救',state.open_remediation_count||0),metric('待重新評量',state.pending_reassessment_count||0),metric('到期複習',Number(state.due_review_count||0)+Number(state.overdue_review_count||0)));text(canonicalState,state.evaluation_state==='EVALUATED'?`尚未精熟：${state.missing_mastery_count}；已保留：${state.retained_required_count}。A2 仍鎖定。`:'完成第一個閱讀或寫作 scored session 後，系統才會建立精熟與複習狀態。')}async function loadProgress(){const value=await api('/api/progress');renderGate(value.active_scored_journey);renderCanonical(value.canonical_learning);progressSummary.replaceChildren(metric('本次學習總數',value.summary.session_count),metric('已結束的本次學習',value.summary.session_completed_count),metric('作答次數',value.summary.attempt_count),metric('需要人工審核',value.summary.pending_human_review_count));progressSkills.replaceChildren();for(const skill of value.skills){progressSkills.append(progressCard(skill.learner_label,skill.activity_status,[`本次學習：${skill.session_count}`,`作答：${skill.attempt_count}`]))}progressUnits.replaceChildren();for(const unit of value.units){progressUnits.append(progressCard(unit.learner_label,unit.activity_status,[unit.learner_title_en,`本次學習：${unit.session_count}`]))}text(progressDebug,JSON.stringify(value.operator_debug,null,2))}
function findLane(lessonId){for(const unit of state.units)for(const lane of unit.lanes)if(lane.lesson_id===lessonId)return{unit,lane};return null}
function updateActivePanel(){activePanel.hidden=!pendingResume;text(activeLabel,pendingResume?`${pendingResume.learner_label||pendingResume.grammar_unit_id}／${pendingResume.session.skill}`:'')}
function renderUnits(){units.replaceChildren();for(const unit of state.units){const button=document.createElement('button');button.className='unit';button.dataset.internalId=unit.internal_grammar_unit_id;button.classList.toggle('selected',Boolean(currentUnit&&currentUnit.internal_grammar_unit_id===unit.internal_grammar_unit_id));button.disabled=locked();const strong=document.createElement('strong');text(strong,unit.learner_label);const small=document.createElement('small');text(small,unit.learner_title_en);button.append(strong,small);button.addEventListener('click',()=>{try{chooseUnit(unit)}catch(error){text(status,error.message)}});units.append(button)}}
function renderLanes(){lanes.replaceChildren();text(laneNote,'');if(!currentUnit)return;for(const lane of currentUnit.lanes){const button=document.createElement('button');button.className='lane';button.classList.toggle('selected',Boolean(currentLane&&currentLane.lesson_id===lane.lesson_id));button.disabled=locked();text(button,lane.learner_label);button.addEventListener('click',()=>begin(lane).catch(error=>text(status,error.message)));lanes.append(button)}}
function chooseUnit(unit){if(locked())throw new Error('請先繼續或放棄目前的本次學習');currentUnit=unit;currentLane=null;items.replaceChildren();renderUnits();renderLanes();text(status,`已選擇：${unit.learner_label}`)}
const serializeTextResponse=(asset,value)=>{const trimmed=value.trim();if(asset.learner_payload.writing_stage==='CONTROLLED_SEQUENCE'||asset.learner_payload.response_type==='sequence')return trimmed.split(/\s+/);return value};function responseFor(card,asset){const tokenBank=asset.learner_payload.token_bank||[];if(tokenBank.length){const bank=document.createElement('div');bank.className='token-bank';tokenBank.forEach(value=>{const chip=document.createElement('span');text(chip,value);bank.append(chip);});card.append(bank);}const options=asset.learner_payload.options||[];if(options.length){const checked=card.querySelector('input[type=radio]:checked');if(!checked)throw new Error('請先選擇答案');return checked.value}const area=card.querySelector('textarea');if(!area||!area.value.trim())throw new Error('請先輸入答案');return serializeTextResponse(asset,area.value)}
async function expose(asset){const result=await api('/api/exposure',{session_id:active.session_id,asset_key:asset.asset_key,expected_session_version:active.session_version});active.session_version=result.session_version;return result}
function renderLane(lane){currentLane=lane;renderUnits();renderLanes();items.replaceChildren();text(laneNote,lane.skill==='SPEAKING'?'口說目前是練習模式：不錄音、不評分，也不代表精熟。':'閱讀與寫作可以重試；只有每一題的最新作答通過或經人工核准，才能完成本次學習。');for(const asset of lane.assets){const card=document.createElement('article');card.className='card';const prompt=document.createElement('p');prompt.className='prompt';text(prompt,asset.learner_payload.prompt);card.append(prompt);const stimulus=asset.learner_payload.stimulus;if(stimulus&&stimulus.body){const block=document.createElement('section');block.className='stimulus';const title=document.createElement('h4');text(title,stimulus.title||'閱讀內容');const body=document.createElement('p');text(body,stimulus.body);block.append(title,body);card.append(block);}const support=asset.learner_payload.support_text;if(support){const note=document.createElement('p');note.className='support-text';text(note,support);card.append(note);}const model=asset.learner_payload.model_language;if(model){const note=document.createElement('p');note.className='model-language';text(note,`示例：${model}`);card.append(note);}const frame=asset.learner_payload.sentence_frame;if(frame){const note=document.createElement('p');note.className='sentence-frame';text(note,`句型：${frame}`);card.append(note);}const options=asset.learner_payload.options||[];if(options.length){const box=document.createElement('div');box.className='options';for(const option of options){const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name=asset.asset_key;input.value=option;label.append(input,document.createTextNode(' '+option));box.append(label)}card.append(box)}else if(asset.learner_payload.response_capture_enabled){const area=document.createElement('textarea');area.setAttribute('aria-label','回答');card.append(area)}const button=document.createElement('button'),result=document.createElement('p');button.className='submit';result.className='result';if(asset.learner_payload.response_capture_enabled){text(button,'送出回答');button.addEventListener('click',async()=>{try{button.disabled=true;await expose(asset);const scored=await api('/api/response',{session_id:active.session_id,asset_key:asset.asset_key,response:responseFor(card,asset),expected_session_version:active.session_version});active.session_version=scored.session_version;text(result,outcomeLabel(scored.outcome));renderGate(scored.completion_gate);await loadProgress()}catch(error){text(status,error.message)}finally{button.disabled=false}})}else{text(button,'完成這張口說練習');button.addEventListener('click',async()=>{try{button.disabled=true;await expose(asset);text(result,'練習已記錄');await loadProgress()}catch(error){text(status,error.message)}finally{button.disabled=false}})}card.append(button,result);items.append(card)}}
async function begin(lane){if(locked())throw new Error('請先繼續或放棄目前的本次學習');active=await api('/api/session/start',{lesson_id:lane.lesson_id});pendingResume=null;updateActivePanel();complete.hidden=false;complete.disabled=true;renderLane(lane);text(status,`本次學習開始：${currentUnit.learner_label}／${lane.learner_label}`);await loadProgress()}
function restore(snapshot){const match=findLane(snapshot.session.lesson_id);if(!match)throw new Error('active_session_bundle_missing');pendingResume=null;active=snapshot.session;currentUnit=match.unit;currentLane=match.lane;updateActivePanel();complete.hidden=false;complete.disabled=true;renderLane(match.lane);text(status,`繼續本次學習：${match.unit.learner_label}／${match.lane.learner_label}`)}
async function finish(path){if(!active)return;const done=await api(path,{session_id:active.session_id,expected_session_version:active.session_version});text(status,sessionStateLabel(done.session_state));active=null;pendingResume=null;currentLane=null;updateActivePanel();complete.hidden=true;complete.disabled=true;gatePanel.hidden=true;items.replaceChildren();renderUnits();renderLanes();await loadProgress()}
complete.addEventListener('click',()=>finish('/api/session/complete').catch(error=>text(status,error.message)));abandon.addEventListener('click',async()=>{try{if(!pendingResume&&!active)return;if(!active)active=pendingResume.session;await finish('/api/session/abandon')}catch(error){text(status,error.message)}});resume.addEventListener('click',()=>{try{if(pendingResume)restore(pendingResume)}catch(error){text(status,error.message)}});refresh.addEventListener('click',()=>loadProgress().catch(error=>text(status,error.message)));
async function start(){state=await api('/api/bootstrap');text(status,'已登入；請選擇一個學習單元');const snapshot=await api('/api/session/active');if(snapshot.active){const match=findLane(snapshot.session.lesson_id);if(!match)throw new Error('active_session_bundle_missing');pendingResume={...snapshot,learner_label:match.unit.learner_label};currentUnit=match.unit;currentLane=match.lane;updateActivePanel();renderUnits();renderLanes()}else if(state.units.length)chooseUnit(state.units[0]);else{renderUnits();renderLanes()}await loadProgress()}
start().catch(error=>text(status,error.message));



const dashboardSummary=document.querySelector('#dashboard-summary'),dashboardState=document.querySelector('#dashboard-state'),reviewList=document.querySelector('#human-review-list'),reviewState=document.querySelector('#human-review-state');let dashboardRole='learner';
function dashboardMetric(label,value){return metric(label,value==null?'—':value)}
function renderRoleDashboard(value){const view=value.dashboard[dashboardRole]||{};dashboardSummary.replaceChildren();if(dashboardRole==='learner'){dashboardSummary.append(dashboardMetric('已完成學習',view.completed_session_count),dashboardMetric('已精熟節點',view.mastered_required_count),dashboardMetric('待補救',view.open_remediation_count),dashboardMetric('到期複習',view.due_review_count));}else if(dashboardRole==='parent'){dashboardSummary.append(dashboardMetric('已完成學習',view.completed_session_count),dashboardMetric('作答次數',view.attempt_count),dashboardMetric('通過',view.pass_count),dashboardMetric('需再練習',view.fail_count));}else{dashboardSummary.append(dashboardMetric('待人工審核',view.pending_human_review_count),dashboardMetric('待補救',view.open_remediation_count),dashboardMetric('待重新評量',view.pending_reassessment_count),dashboardMetric('到期複習',view.due_review_count));}text(dashboardState,`目前顯示：${dashboardRole==='learner'?'學習者':dashboardRole==='parent'?'家長':'教師'}視圖。`);document.querySelector('#human-review-panel').hidden=dashboardRole!=='teacher';}
async function loadDashboard(){const value=await api('/api/dashboard');renderRoleDashboard(value);}
function reviewCheckbox(label,key){const wrapper=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.dataset.criteria=key;wrapper.append(input,document.createTextNode(` ${label}`));return wrapper;}
async function submitReview(card,row){const criteria={};card.querySelectorAll('[data-criteria]').forEach(input=>{criteria[input.dataset.criteria]=input.checked;});const decision=card.querySelector('select').value,notes=card.querySelector('textarea').value;const response=await api('/api/human-review/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({attempt_id:row.attempt_id,decision,criteria,notes})});text(reviewState,`審核完成：${response.review_result.outcome}`);await Promise.all([loadDashboard(),loadHumanReviews()]);}
function renderHumanReviews(value){reviewList.replaceChildren();if(!value.review_queue.length){text(reviewState,'目前沒有待人工審核項目。');return;}text(reviewState,`待審核 ${value.pending_count} 項。`);for(const row of value.review_queue){const card=document.createElement('article');card.className='review-card';const title=document.createElement('h4');text(title,`${row.skill} · ${row.role}`);const response=document.createElement('pre');response.className='review-response';text(response,typeof row.response==='string'?row.response:JSON.stringify(row.response));const select=document.createElement('select');for(const choice of ['APPROVE','REJECT','DEFER']){const option=document.createElement('option');option.value=choice;text(option,choice);select.append(option);}const notes=document.createElement('textarea');notes.placeholder='審核備註';const button=document.createElement('button');button.type='button';text(button,'送出審核');button.addEventListener('click',()=>submitReview(card,row));card.append(title,response,reviewCheckbox('文法目標符合','grammar_target_match'),reviewCheckbox('語意符合情境','meaning_matches_context'),reviewCheckbox('回答完整','complete_response'),select,notes,button);reviewList.append(card);}}
async function loadHumanReviews(){const value=await api('/api/human-review');renderHumanReviews(value);}
document.querySelectorAll('[data-dashboard-role]').forEach(button=>button.addEventListener('click',async()=>{dashboardRole=button.dataset.dashboardRole;await loadDashboard();if(dashboardRole==='teacher')await loadHumanReviews();}));
document.addEventListener('DOMContentLoaded',async()=>{try{await loadDashboard();await loadHumanReviews();}catch(error){text(dashboardState,error.message);}});


const unit01CoverageButton=document.querySelector('#load-unit01-coverage'),unit01CoverageSummary=document.querySelector('#unit01-coverage-summary'),unit01CoverageState=document.querySelector('#unit01-coverage-state');
function coverageMetric(label,value,percentage){const shown=percentage==null?String(value??'—'):`${value} (${percentage}%)`;return metric(label,shown)}
function renderUnit01Coverage(value){const domains=value.coverage_by_domain||{},evp=domains.evp_senses||{},egp=domains.egp_rows||{},patterns=domains.assessment_patterns||{},evidence=value.learner_evidence_summary||{};unit01CoverageSummary.replaceChildren();unit01CoverageSummary.append(coverageMetric('正式題目',value.curriculum_item_count,null),coverageMetric('已練習題目',evidence.distinct_attempted_item_count,null),coverageMetric('EVP 已練習',evp.practised_count,evp.practised_percentage),coverageMetric('EGP 已練習',egp.practised_count,egp.practised_percentage),coverageMetric('題型已練習',patterns.practised_count,patterns.practised_percentage));text(unit01CoverageState,`Cambridge stage：${value.cambridge_stage}；KET activity bridge：${value.ket_prerequisite_readback.activity_bridge_status}。`);}
async function loadUnit01Coverage(){try{text(unit01CoverageState,'讀取中…');const value=await api('/api/unit01-coverage');renderUnit01Coverage(value);}catch(error){text(unit01CoverageState,`讀取失敗：${error.message}`);}}
if(unit01CoverageButton)unit01CoverageButton.addEventListener('click',loadUnit01Coverage);
