from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Callable, Mapping

from product.a1fs_v1_2_1 import u01qb18h_r1_unit01_twelve_form_learner_pdf_materialization as u01_pdf
from product.a1fs_v1_2_1 import u04formv3a_direct_authored_form01_04_validator as formv3a
from product.a1fs_v1_2_1 import u04q10r1_unit04_learner_facing_pedagogical_acceptance as learner_renderer
from product.a1fs_v1_2_1 import u04q10r2_unit04_learner_pdf_materialization_and_visual_acceptance as q10r2
from product.a1fs_v1_2_1 import u04q10r2r1_unit04_actual_pdf_pagination_repair as pagination

A1FS_CONTENT_POLICY_MODE = "NOT_CONTENT_PRODUCER"
A1FS_CONTENT_POLICY_EXEMPTION = (
    "Read-only presentation consumer over GPT-5.6-direct-authored FormV3A static assets. "
    "It maps existing fields into the already-merged Unit04 learner renderer, restores "
    "the already-approved Unit01 worksheet response-space CSS, reuses the merged Unit04 "
    "pagination guard and Chromium chain, and authors no learner-facing task content."
)

PROGRAM_ID = "A1FS-V1"
UNIT_ID = "GRAMMAR_BASIC_PREPOSITIONS_PLACE"
TASK_ID = "A1FS-V1-U04FORMV3B_ExistingRendererIntegrationAndActualForm01To04VisualReview"
STATUS = "PASS_A1FS_V1_U04FORMV3B_EXISTING_RENDERER_MACHINE_INTEGRATION"
REVISION = "FORMV3B_EXISTING_RENDERER_WORKSHEET_PRESENTATION_V1"
NEXT_SHORT_STEP = "A1FS-V1-U04FORMV3B_R1_ActualForm01To04PdfHumanVisualPedagogicalAcceptance"
FORM_COUNT = 4
QUESTIONS_PER_FORM = 40
TOTAL_QUESTIONS = 160
DEFAULT_OUTPUT_ROOT = Path(".local/a1fs_v1/review/unit04_formv3_form01_04_visual_acceptance")
MANIFEST_NAME = "unit04_formv3_form01_04_visual_acceptance.private.json"

SECTION_TITLES = {
    "A": "A · Understand the place",
    "B": "B · Read and find evidence",
    "C": "C · Write from the evidence",
    "D": "D · Understand people, objects, and actions",
    "E": "E · Write and speak",
}
SECTION_COUNTS = {"A": 6, "B": 10, "C": 10, "D": 8, "E": 6}

# Core response/pagination presentation rules copied from the already-approved Unit01
# learner worksheet renderer. No learner English is generated by these styles.
WORKSHEET_STYLE_ID = "u04-formv3b-approved-worksheet-css"
WORKSHEET_CSS = """
@page{size:A4;margin:10mm 10mm 12mm}
*{box-sizing:border-box}
html,body{margin:0;padding:0;font-family:Arial,"Noto Sans",sans-serif;color:#17202a;background:#fff}
body{font-size:10.5pt;line-height:1.3}
body>h1{font-size:20pt;margin:0 0 2px;line-height:1.12;border-bottom:2px solid #26394d;padding-bottom:5px}
body>p{margin:0 0 7px;color:#566573;font-size:9.5pt}
.unit04-section{margin:0 0 8px;break-inside:auto}
.unit04-section>h2{font-size:14pt;margin:4px 0 5px;border-left:4px solid #34495e;padding:3px 7px;background:#f5f7f8;break-after:avoid;page-break-after:avoid}
.activity{break-inside:avoid;border:1px solid #d5d8dc;border-radius:6px;padding:5px 7px;margin:0 0 4px}
.activity-heading{display:flex;align-items:center;gap:7px;margin-bottom:3px}
.question-number{font-weight:800;font-size:10.5pt}
.skill-pill{font-size:8pt;font-weight:700;border:1px solid #aeb6bf;border-radius:999px;padding:1px 6px;color:#455a64}
.stimulus{font-size:11.3pt;font-weight:700;padding:4px 6px;margin:2px 0 4px;background:#f8f9f9;border-radius:4px}
.prompt{font-size:10.5pt;margin:2px 0 4px}
.choices{display:grid;grid-template-columns:1fr 1fr;gap:4px 10px}
.choice{display:flex;align-items:flex-start;gap:5px;min-height:18px}
.choice-mark{width:12px;height:12px;border:1.4px solid #566573;border-radius:50%;display:inline-block;flex:0 0 12px;margin-top:2px}
.choice-label{font-weight:700;min-width:17px}
.write-line{height:16px;border-bottom:1px solid #99a3a4;margin:2px 0}
.speaking-box{border:1px dashed #85929e;border-radius:5px;padding:5px;margin-top:3px}
.speaking-icon{font-size:8.5pt;font-weight:700;color:#566573}
.speaking-space{height:12px}
""".strip()


class Unit04FormV3BError(ValueError):
    pass


def _root(repo_root: Path | str | None = None) -> Path:
    return Path(repo_root).resolve() if repo_root is not None else Path(__file__).resolve().parents[2]


def _file_identity(path: Path) -> dict[str, Any]:
    raw = Path(path).read_bytes()
    return {"bytes": len(raw), "sha256": hashlib.sha256(raw).hexdigest()}


def _learner_skill(question: Mapping[str, Any]) -> str:
    if str(question.get("modality") or "") == "ORAL":
        return "SPEAKING"
    skill = str(question.get("skill") or "")
    if "WRITING" in skill:
        return "WRITING"
    if skill == "GRAMMAR":
        return "GRAMMAR"
    return "READING"


def _project_form(payload: Mapping[str, Any]) -> dict[str, Any]:
    form = dict(payload.get("form") or {})
    contexts = {str(row["slot"]): dict(row) for row in form.get("contexts") or []}
    questions = list(form.get("questions") or [])
    if len(questions) != QUESTIONS_PER_FORM:
        raise Unit04FormV3BError(f"QUESTION_COUNT_DRIFT:{len(questions)}")

    activities: list[dict[str, Any]] = []
    seen_section_context: set[tuple[str, str]] = set()
    for question in questions:
        section = str(question["section"])
        slot = str(question["context_slot"])
        key = (section, slot)
        passage = str(contexts[slot]["passage"]) if key not in seen_section_context else ""
        seen_section_context.add(key)

        oral = str(question.get("modality") or "") == "ORAL"
        response_mode = "practice_only" if oral else str(question["response_mode"])
        activity = {
            "question_number": f"Q{int(question['question_number']):02d}",
            "skill": _learner_skill(question),
            "stimulus": passage,
            "prompt": str(question["prompt"]),
            "response_mode": response_mode,
        }
        if response_mode == "select_one":
            activity["options"] = list(question.get("options") or [])
        activities.append(activity)

    return {
        "form_id": str(form["form_id"]),
        "form_ordinal": int(form["form_number"]),
        "progression_stage": str(form["stage"]),
        "sections": [
            {"section": section, "section_name": SECTION_TITLES[section], "activity_count": SECTION_COUNTS[section]}
            for section in ("A", "B", "C", "D", "E")
        ],
        "activities": activities,
    }


def load_projected_formv3a_forms(repo_root: Path | str | None = None) -> list[dict[str, Any]]:
    root = _root(repo_root)
    validation = formv3a.build_unit04_formv3a_validation(root)
    if validation.get("status") != formv3a.STATUS:
        raise Unit04FormV3BError("FORMV3A_SOURCE_NOT_PASS")
    forms = [
        _project_form(formv3a._load_asset(root, ordinal))
        for ordinal in formv3a.EXPECTED_FORMS
    ]
    if [row["form_ordinal"] for row in forms] != [1, 2, 3, 4]:
        raise Unit04FormV3BError("FORM_SEQUENCE_DRIFT")
    return forms


def inject_approved_worksheet_css(rendered_html: str) -> str:
    html = str(rendered_html)
    if WORKSHEET_STYLE_ID in html:
        raise Unit04FormV3BError("WORKSHEET_STYLE_ALREADY_PRESENT")
    marker = "</head>"
    if html.count(marker) != 1:
        raise Unit04FormV3BError(f"HTML_HEAD_BOUNDARY_INVALID:{html.count(marker)}")
    style = f'<style id="{WORKSHEET_STYLE_ID}">{WORKSHEET_CSS}</style>'
    return html.replace(marker, style + marker, 1)


def render_formv3a_with_existing_renderer(form: Mapping[str, Any]) -> str:
    # The only HTML renderer called here is the merged Unit04 Q10R1 renderer.
    html = learner_renderer.render_form_html(form)
    html = inject_approved_worksheet_css(html)
    html = pagination.inject_pdf_pagination_guards(html)
    if html.count('<article class="activity">') != QUESTIONS_PER_FORM:
        raise Unit04FormV3BError("RENDERED_ACTIVITY_COUNT_DRIFT")
    return html


def build_machine_integration_report(repo_root: Path | str | None = None) -> dict[str, Any]:
    forms = load_projected_formv3a_forms(repo_root)
    rendered = [render_formv3a_with_existing_renderer(form) for form in forms]
    oral_counts = [
        sum(
            'class="speaking-box"' in u01_pdf._activity_html(activity, index + 1)
            for index, activity in enumerate(form["activities"])
        )
        for form in forms
    ]
    return {
        "task_id": TASK_ID,
        "status": STATUS,
        "revision": REVISION,
        "form_count": len(forms),
        "question_count": sum(len(form["activities"]) for form in forms),
        "html_activity_count": sum(html.count('<article class="activity">') for html in rendered),
        "worksheet_css_form_count": sum(WORKSHEET_STYLE_ID in html for html in rendered),
        "pagination_guard_form_count": sum(pagination.PDF_PAGINATION_STYLE_ID in html for html in rendered),
        "speaking_response_form_counts": oral_counts,
        "renderer_task_id": learner_renderer.TASK_ID,
        "renderer_reused": True,
        "second_renderer_created": False,
        "python_learner_content_authoring_used": False,
        "current360_passage_mutated": False,
        "listening_modified": False,
        "a2_a2plus_unlocked": False,
        "human_visual_review": "PENDING_ACTUAL_PDF_EVIDENCE",
        "human_pedagogical_review": "PENDING_ACTUAL_PDF_EVIDENCE",
        "next_short_step": NEXT_SHORT_STEP,
    }


def materialize_form01_04_pdfs(
    *,
    output_root: Path = DEFAULT_OUTPUT_ROOT,
    chromium_path: Path | None = None,
    browser_runner: Callable[..., Mapping[str, Any]] | None = None,
    pdf_page_counter: Callable[[Path], int] | None = None,
    repo_root: Path | str | None = None,
) -> dict[str, Any]:
    forms = load_projected_formv3a_forms(repo_root)
    output_root = Path(output_root).resolve()
    html_root = output_root / "html"
    pdf_root = output_root / "pdf"
    html_root.mkdir(parents=True, exist_ok=True)
    pdf_root.mkdir(parents=True, exist_ok=True)

    chromium = (
        Path(chromium_path).resolve(strict=True)
        if chromium_path is not None
        else q10r2.chromium_acceptance.discover_chromium()
    )
    run_browser = browser_runner or q10r2.UNIT01_HEADERLESS_BROWSER_RUNNER
    count_pages = pdf_page_counter or q10r2.UNIT01_PDF_PAGE_COUNTER

    artifacts: list[dict[str, Any]] = []
    for form in forms:
        ordinal = int(form["form_ordinal"])
        html_path = html_root / f"Form{ordinal:02d}.html"
        pdf_path = pdf_root / f"Form{ordinal:02d}.pdf"
        rendered = render_formv3a_with_existing_renderer(form)
        u01_pdf._atomic_text(html_path, rendered)
        result = dict(run_browser(chromium, source_html=html_path, output_path=pdf_path, mode="PDF"))
        if not pdf_path.is_file():
            raise Unit04FormV3BError(f"PDF_OUTPUT_MISSING:F{ordinal:02d}")
        identity = _file_identity(pdf_path)
        if identity["bytes"] < 1024:
            raise Unit04FormV3BError(f"PDF_OUTPUT_TOO_SMALL:F{ordinal:02d}:{identity['bytes']}")
        page_count = int(count_pages(pdf_path))
        if page_count < 1:
            raise Unit04FormV3BError(f"PDF_PAGE_COUNT_INVALID:F{ordinal:02d}:{page_count}")
        artifacts.append({
            "form_id": form["form_id"],
            "form_ordinal": ordinal,
            "html_relative_path": f"html/Form{ordinal:02d}.html",
            "pdf_relative_path": f"pdf/Form{ordinal:02d}.pdf",
            "pdf_bytes": identity["bytes"],
            "pdf_sha256": identity["sha256"],
            "page_count": page_count,
            "browser_render": {k: v for k, v in result.items() if k not in {"source_path", "output_path"}},
            "human_visual_review": "PENDING",
            "human_pedagogical_review": "PENDING",
        })

    if len(artifacts) != FORM_COUNT:
        raise Unit04FormV3BError(f"PDF_COUNT_DRIFT:{len(artifacts)}")
    if len({row["pdf_sha256"] for row in artifacts}) != FORM_COUNT:
        raise Unit04FormV3BError("PDF_SHA256_NOT_DISTINCT")

    manifest = {
        "schema_version": "a1fs.v1.u04.formv3b.actual_pdf_manifest.v1",
        "task_id": TASK_ID,
        "machine_status": STATUS,
        "form_count": FORM_COUNT,
        "question_count": TOTAL_QUESTIONS,
        "materialized_pdf_count": FORM_COUNT,
        "renderer_reused": learner_renderer.TASK_ID,
        "pagination_reused": pagination.TASK_ID,
        "chromium_chain_reused": q10r2.TASK_ID,
        "python_learner_content_authoring_used": False,
        "artifacts": artifacts,
        "human_visual_review_pending_count": FORM_COUNT,
        "human_pedagogical_review_pending_count": FORM_COUNT,
        "human_acceptance": "PENDING_ACTUAL_PDF_REVIEW",
        "next_short_step": NEXT_SHORT_STEP,
    }
    u01_pdf._atomic_json(output_root / MANIFEST_NAME, manifest)
    return manifest


def main() -> int:
    print(json.dumps(build_machine_integration_report(), ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
