from __future__ import annotations
import json
from collections import Counter
from pathlib import Path
from typing import Any

A1FS_CONTENT_POLICY_MODE="VALIDATOR_ONLY"
A1FS_CONTENT_POLICY_EXEMPTION=(
    "Validates GPT-5.6-authored media-dependent KET336 contracts and exact source binding. "
    "No audio, visual assets, or learner English are generated by this validator."
)
TASK_ID="A1FS-V1-U05FAR7_KETAssetDependent336GPT56LearnerFacingMaterialization"
STATUS="PASS_A1FS_V1_U05FAR7_KET_MEDIA336_GPT56_MATERIALIZATION"
NEXT_SHORT_STEP="A1FS-V1-U05FAR7_Dictation480GPT56SegmentMaterialization"

ROOT=Path(__file__).resolve().parents[2]; DATA=ROOT/"product/a1fs_v1_2_1/data"
KET=DATA/"unit05_ket_adapted_practice_672.json"
SPOKEN=DATA/"unit05_spoken360_360.json"
CURRENT=DATA/"unit05_current360_360.json"
PATTERN=DATA/"unit05_pattern360_360.json"

MEDIA_FAMILIES={
 "PICTURE_SEQUENCE_STORY","AUDIO_PICTURE_DETAIL_SELECTION","AUDIO_NOTE_COMPLETION",
 "AUDIO_CONVERSATION_DETAIL","SHORT_AUDIO_GIST_INTENT_DETAIL","AUDIO_LIST_MATCHING",
 "COLLABORATIVE_VISUAL_DISCUSSION",
}
TEXT_FAMILIES={
 "SHORT_MESSAGE_MEANING","PERSON_TEXT_DETAIL_MATCHING","LONG_TEXT_DETAIL_INFERENCE",
 "LEXICAL_CLOZE","OPEN_CLOZE","SHORT_COMMUNICATIVE_EMAIL","PERSONAL_INTERVIEW",
}

class U05FAR7KETMediaError(ValueError): pass
def _load(p:Path)->dict[str,Any]:
 x=json.loads(p.read_text(encoding="utf-8"))
 if not isinstance(x,dict): raise U05FAR7KETMediaError(f"NOT_OBJECT:{p}")
 return x
def _req(ok:bool,code:str)->None:
 if not ok: raise U05FAR7KETMediaError(code)
def _transcript(entry:dict[str,Any])->list[dict[str,str]]:
 return [{"speaker":x["speaker"],"text":x["text"]} for x in entry["dialogue_turns"]]

def build_report()->dict[str,Any]:
 ket,spoken,current,pattern=map(_load,(KET,SPOKEN,CURRENT,PATTERN))
 spoken_by={x["reader_entry_id"]:x for x in spoken["entries"]}
 current_by={x["episode_id"]:x for x in current["episodes"]}
 pattern_ids={x["reader_entry_id"] for x in pattern["entries"]}
 _req(ket["item_count"]==672 and len(ket["items"])==672,"KET_DENOMINATOR_DRIFT")
 _req(ket["authored_item_count"]==672,"KET_AUTHOR_COUNT_DRIFT")
 _req(ket["executable_text_only_count"]==336,"TEXT_EXECUTABLE_COUNT_DRIFT")
 _req(ket["asset_pending_count"]==336,"ASSET_PENDING_COUNT_DRIFT")
 _req(ket["status"]=="PASS_KET672_GPT56_AUTHORED_336_TEXT_EXECUTABLE_336_ASSET_PENDING","STATUS_DRIFT")
 mc=ket["media_dependent_static_contract"]
 _req(mc["author_model"]=="GPT-5.6 Sol" and mc["review_status"]=="PASS","MEDIA_CONTRACT_REVIEW_DRIFT")
 _req(mc["audio_assets_generated"] is False and mc["visual_assets_generated"] is False,"MEDIA_ASSET_PREMATURELY_GENERATED")

 counts=Counter(); audio=visual=audio_visual=0; list_bundles=0
 reviews=("gpt56_semantic_review","gpt56_pedagogical_review","gpt56_source_grounding_review","gpt56_unit05_scope_review","gpt56_answerability_review")
 for row in ket["items"]:
  fam=row["task_family"]
  if fam in TEXT_FAMILIES:
   _req(row["execution_status"]=="EXECUTABLE_TEXT_ONLY",f"TEXT_EXECUTION_DRIFT:{row['practice_id']}")
   continue
  _req(fam in MEDIA_FAMILIES,f"UNKNOWN_MEDIA_FAMILY:{fam}")
  counts[fam]+=1
  _req(row["materialization_status"]=="MATERIALIZED_GPT56_MEDIA_CONTRACT_REVIEW_PASS_ASSET_PENDING",f"MEDIA_STATUS_DRIFT:{row['practice_id']}")
  _req(row["execution_status"]=="NOT_EXECUTABLE_ASSET_PENDING",f"MEDIA_EXECUTION_DRIFT:{row['practice_id']}")
  _req(all(row[k]=="PASS" for k in reviews),f"GPT56_REVIEW_NOT_PASS:{row['practice_id']}")
  _req(isinstance(row["learner_facing_content"],dict) and isinstance(row["response_contract"],dict) and isinstance(row["answer_binding_or_rubric"],dict),f"MEDIA_CONTENT_MISSING:{row['practice_id']}")
  pre=set(row["asset_preconditions"])
  if pre=={"AUDIO_ASSET_BOUND"}: audio+=1
  elif pre=={"VISUAL_ASSET_BOUND"}: visual+=1
  elif pre=={"AUDIO_ASSET_BOUND","VISUAL_ASSET_BOUND"}: audio_visual+=1
  else: raise U05FAR7KETMediaError(f"MEDIA_ASSET_GATE_DRIFT:{row['practice_id']}:{pre}")

  content=row["learner_facing_content"]; stim=content["stimulus"]; answer=row["answer_binding_or_rubric"]

  if fam=="PICTURE_SEQUENCE_STORY":
   ref=stim["source_ref"]; _req(ref in current_by,f"PICTURE_SOURCE_MISSING:{row['practice_id']}")
   _req(stim["source_context"]==current_by[ref]["paragraph"],f"PICTURE_SOURCE_CONTEXT_DRIFT:{row['practice_id']}")
   _req(2<=len(stim["panels"])<=3,f"PICTURE_PANEL_COUNT_DRIFT:{row['practice_id']}")
   _req(all(p["source_fact"] in stim["source_context"] and p["asset_state"]=="PENDING_VISUAL_MATERIALIZATION" for p in stim["panels"]),f"PICTURE_PANEL_SOURCE_DRIFT:{row['practice_id']}")
   _req(answer["model_response_role"]=="EXAMPLE_NOT_SINGLE_ANSWER",f"PICTURE_MODEL_ROLE_DRIFT:{row['practice_id']}")

  elif fam in {"AUDIO_PICTURE_DETAIL_SELECTION","AUDIO_NOTE_COMPLETION","AUDIO_CONVERSATION_DETAIL","SHORT_AUDIO_GIST_INTENT_DETAIL"}:
   ref=stim["source_ref"]; _req(ref in spoken_by,f"AUDIO_SOURCE_MISSING:{row['practice_id']}")
   _req(stim["audio_transcript_authority"]==_transcript(spoken_by[ref]),f"AUDIO_TRANSCRIPT_DRIFT:{row['practice_id']}")
   _req(stim["learner_visible_transcript"] is False,f"AUDIO_TRANSCRIPT_VISIBLE:{row['practice_id']}")
   if fam=="AUDIO_PICTURE_DETAIL_SELECTION":
    _req(answer["correct_option_id"]=="A",f"AUDIO_PICTURE_KEY_DRIFT:{row['practice_id']}")
    _req(answer["evidence_text"] in [x["text"] for x in stim["audio_transcript_authority"]],f"AUDIO_PICTURE_EVIDENCE_DRIFT:{row['practice_id']}")
    _req(len(stim["visual_option_briefs"])==3,f"AUDIO_PICTURE_VISUAL_OPTION_COUNT_DRIFT:{row['practice_id']}")
   elif fam=="AUDIO_NOTE_COMPLETION":
    _req(len(row["response_contract"]["fields"])==2,f"NOTE_FIELD_COUNT_DRIFT:{row['practice_id']}")
    _req(set(answer["answers"])=={"1","2"},f"NOTE_ANSWER_SHAPE_DRIFT:{row['practice_id']}")
    lines=[x["text"] for x in stim["audio_transcript_authority"]]
    _req(all(answer["source_lines"][k] in lines for k in ("1","2")),f"NOTE_SOURCE_LINE_DRIFT:{row['practice_id']}")
   elif fam=="AUDIO_CONVERSATION_DETAIL":
    _req(answer["correct_option_id"]=="A" and answer["evidence_text"] in [x["text"] for x in stim["audio_transcript_authority"]],f"AUDIO_DETAIL_KEY_DRIFT:{row['practice_id']}")
   else:
    _req(answer["correct_option_id"]=="A",f"GIST_KEY_DRIFT:{row['practice_id']}")
    _req(answer["source_scene_ref"]==spoken_by[ref]["source_episode_id"],f"GIST_SOURCE_SCENE_DRIFT:{row['practice_id']}")

  elif fam=="AUDIO_LIST_MATCHING":
   extracts=stim["extracts"]; refs=[x["source_ref"] for x in extracts]
   _req(len(refs)==3 and len(set(refs))==3,f"AUDIO_LIST_SOURCE_BUNDLE_DRIFT:{row['practice_id']}")
   _req(row["reader_source_refs"]==refs,f"AUDIO_LIST_READER_REFS_DRIFT:{row['practice_id']}")
   for x in extracts:
    _req(x["source_ref"] in spoken_by and x["transcript_authority"]==_transcript(spoken_by[x["source_ref"]]),f"AUDIO_LIST_TRANSCRIPT_DRIFT:{row['practice_id']}:{x['source_ref']}")
   bundle=row["source_bundle_review"]
   _req(bundle and bundle["status"]=="PASS_GPT56_SOURCE_BUNDLE_REVIEW" and bundle["source_refs"]==refs,f"AUDIO_LIST_BUNDLE_REVIEW_DRIFT:{row['practice_id']}")
   _req(answer["matches"]=={"1":"A","2":"B","3":"C"},f"AUDIO_LIST_KEY_DRIFT:{row['practice_id']}")
   list_bundles+=1

  elif fam=="COLLABORATIVE_VISUAL_DISCUSSION":
   opts=stim["visual_options"]; _req(len(opts)==3,f"VISUAL_DISCUSSION_OPTION_COUNT_DRIFT:{row['practice_id']}")
   for opt in opts:
    _req(opt["source_ref"] in current_by and opt["description"]==current_by[opt["source_ref"]]["paragraph"],f"VISUAL_DISCUSSION_SOURCE_DRIFT:{row['practice_id']}:{opt['id']}")
    _req(opt["asset_state"]=="PENDING_VISUAL_MATERIALIZATION",f"VISUAL_DISCUSSION_ASSET_STATE_DRIFT:{row['practice_id']}")
   _req(answer["model_response_role"]=="EXAMPLE_NOT_SINGLE_ANSWER",f"VISUAL_DISCUSSION_MODEL_ROLE_DRIFT:{row['practice_id']}")
   _req("correct_option_id" not in answer,f"VISUAL_DISCUSSION_SINGLE_ANSWER_FORBIDDEN:{row['practice_id']}")
   _req(any(r in pattern_ids for r in row["reader_source_refs"]),f"VISUAL_DISCUSSION_PATTERN_GROUNDING_MISSING:{row['practice_id']}")

 _req(counts==Counter({f:48 for f in MEDIA_FAMILIES}),f"MEDIA_FAMILY_COUNTS_DRIFT:{dict(counts)}")
 _req(list_bundles==48,"AUDIO_LIST_BUNDLE_COUNT_DRIFT")
 _req((audio,visual,audio_visual)==(192,96,48),f"MEDIA_GATE_TOTALS_DRIFT:{audio}:{visual}:{audio_visual}")
 return {
  "task_id":TASK_ID,"status":STATUS,"ket_authored_count":672,
  "text_executable_count":336,"media_asset_pending_count":336,
  "media_family_counts":dict(counts),"audio_only_count":audio,"visual_only_count":visual,
  "audio_visual_count":audio_visual,"audio_list_bundle_review_pass_count":list_bundles,
  "actual_media_assets_generated":0,"next_short_step":NEXT_SHORT_STEP,
 }

def main()->int:
 print(json.dumps(build_report(),ensure_ascii=False,indent=2)); return 0
if __name__=="__main__": raise SystemExit(main())
