"""Validate GPT-6 authored Unit06 Writing360 batches against source and mapping.

The code checks evidence and structure, not independent semantic judgement.
Learner-facing English is never generated by this validator.
"""
import json
import re
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
DATA=ROOT/"product/a1fs_v1_2_1/data"
PILOT=DATA/"unit06_writing360_pilot15_approved.json"
SOURCE=DATA/"unit06_current360_360.json"
MAPPING=DATA/"unit06_writing360_360.json"
OPS={"COPY_AND_CHANGE","TABLE_TO_SENTENCES","SENTENCE_PLAN","GUIDED_MINI_TEXT"}
BAN=re.compile(r"\b(children|clothes|feet|women|men|people|mice|geese|teeth|was|were|cannot|can't)\b",re.I)
CAN_BAD=re.compile(r"\bcan\s+(not|to)\b",re.I)

def read(path):
    return json.loads(path.read_text(encoding="utf-8"))

def check(ok,code):
    if not ok:
        raise ValueError(code)

def validate():
    pilot=read(PILOT); source=read(SOURCE); mapping=read(MAPPING)
    episodes={e["episode_id"]:e for e in source["episodes"]}
    pilots={e["source_episode_id"]:e for e in pilot["pilots"]}
    rows=mapping["entries"]
    check(len(episodes)==len(rows)==360,"SOURCE_MAPPING_360")
    check(len(pilots)==15 and pilot["human_acceptance_status"]=="PILOT15_APPROVED_BY_OPERATOR","PILOT15")
    check(pilot["admission_rule"]["model_author"]=="GPT-6"
          and pilot["admission_rule"]["programmatic_content_generation_permitted"] is False,
          "MODEL_AUTHORITY")
    check(mapping["full360_materialization_allowed"] is False,"FULL360_PREMATURE_UNLOCK")
    check(mapping["status"]=="SOURCE_PURPOSE_MAPPING_WITH_GPT6_AUTHORING_BATCHES_PARTIAL",
          "MAPPING_PARTIAL_STATUS")
    files=mapping["content_batch_refs"]
    check(files and len(files)==len(set(files)),"BATCH_FILE_LIST")
    authored={}
    counts={o:0 for o in OPS}
    for file_ref in files:
        path=ROOT/file_ref
        check(path.parent==DATA and path.suffix==".json" and path.is_file(),
              f"BATCH_PATH:{file_ref}")
        batch=read(path)
        entries=batch["entries"]
        check(batch["authoring_model"]==batch["review_model"]=="GPT-6"
              and batch["review_mode"]=="SAME_MODEL_EDITORIAL_SELF_REVIEW_NOT_INDEPENDENT"
              and batch["programmatic_english_generation"] is False
              and len(entries)==batch["entry_count"],f"BATCH_METADATA:{file_ref}")
        for entry in entries:
            sid=entry["source_episode_id"]
            check(sid not in authored and sid in episodes,f"BATCH_DUPLICATE_SOURCE:{sid}")
            authored[sid]=(entry,file_ref)
    check(len(authored)==mapping["gpt6_authored_self_reviewed_count"],"AUTHORED_COUNT_DRIFT")
    check(mapping["mapping_only_pending_authoring_count"]==345-len(authored),
          "PENDING_DENOMINATOR")
    check(mapping["total_authored_content_count_including_pilot"]==15+len(authored),
          "TOTAL_CONTENT_COUNT")
    check(pilot["admission_rule"]["remaining_entries"]==345-len(authored),
          "PILOT_POLICY_PROGRESS")
    check(pilot["admission_rule"]["gpt6_authored_self_reviewed_entries"]==len(authored),
          "PILOT_POLICY_AUTHORED")
    for i,row in enumerate(rows,1):
        sid=f"U06-NEB-E{i:03d}";rid=f"U06-WRITE-E{i:03d}"
        src=episodes[sid]
        check(row["source_episode_id"]==sid and row["writing_entry_id"]==rid
              and row["source_episode_slot_id"]==src["episode_slot_id"]
              and row["target_chunk_surfaces"]==src["target_chunk_surfaces"],
              f"MAPPING_LINEAGE:{rid}")
        evidence=row["source_evidence"]
        check(all(evidence[k] in src["paragraph"] for k in
                  ("scene_intro_exact","detail_exact","ability_exact")),
              f"MAPPING_SOURCE_EVIDENCE:{rid}")
        check(row["writing_operation"] in OPS and row["writing_focus_zh"]
              and row["operation_selection_reason_zh"],f"WRITING_PURPOSE:{rid}")
        counts[row["writing_operation"]]+=1
        check(not any(k in row for k in ("learner_page","teacher_only","model_answer")),
              f"MODEL_TEXT_IN_MAPPING:{rid}")
        if sid in pilots:
            check(row["writing_content_status"]=="PILOT_APPROVED_REFER_TO_CANONICAL_PILOT15"
                  and row["pilot_id"]==pilots[sid]["id"]
                  and row["writing_operation"]==pilots[sid]["operation"],
                  f"PILOT_MAPPING:{rid}")
            continue
        if sid not in authored:
            check(row["writing_content_status"]=="MAPPING_ONLY_AWAIT_GPT6_PER_ENTRY_AUTHORING"
                  and row["pilot_id"] is None,f"FALSE_AUTHORING:{rid}")
            continue
        entry,ref=authored[sid]
        check(row["writing_content_status"]=="GPT6_MODEL_AUTHORED_SELF_REVIEW_PASS"
              and row["gpt6_authored_self_reviewed"] is True
              and row["authoring_content_ref"]==f"{ref}#{rid}",
              f"BATCH_MAPPING_LINK:{rid}")
        check(entry["writing_entry_id"]==rid and entry["source_episode_id"]==sid
              and entry["source_episode_slot_id"]==src["episode_slot_id"]
              and entry["target_chunk_surfaces"]==src["target_chunk_surfaces"]
              and entry["operation"]==row["writing_operation"],
              f"BATCH_SOURCE_ID:{rid}")
        answer=entry["model_answer"]
        lp=entry["learner_page"]; ta=entry["teacher_only"]
        check(2<=len(answer)<=4 and all(x.endswith(".") for x in answer)
              and entry["full_model_text"]==" ".join(answer)
              and all(t.casefold() in entry["full_model_text"].casefold()
                      for t in src["target_chunk_surfaces"]),
              f"BATCH_ANSWER:{rid}")
        check(lp["fact_card"] and lp["word_bank"]
              and lp["worked_example"]["complete_sentence"]==answer[0]
              and len(lp["write_sentence_steps"])==len(answer)
              and len(lp["sentence_plan"])==len(answer)
              and lp["blank_full_version_line_count"]==len(answer)
              and lp["full_version_task"],f"BATCH_LEARNER_SUPPORT:{rid}")
        check(ta["model_answer"]==answer and ta["show_after_submission"] is True,
              f"BATCH_ANSWER_KEY:{rid}")
        auth=entry["authoring_evidence"]; qa=entry["review_evidence"]
        check(auth["model"]=="GPT-6" and auth["source_episode_id"]==sid
              and auth["source_ref"] and auth["content_provenance_ref"]==f"{ref}#{rid}",
              f"BATCH_AUTHORSHIP_EVIDENCE:{rid}")
        check(qa["model"]=="GPT-6"
              and qa["review_mode"]=="SAME_MODEL_EDITORIAL_SELF_REVIEW_NOT_INDEPENDENT"
              and qa["review_note"] and qa["review_ref"]
              and all(qa[k]=="PASS" for k in
                      ("semantic","pedagogical_answerability","grammar_ceiling",
                       "source_fact_grounding","writing_operation_fit")),
              f"BATCH_QA_EVIDENCE:{rid}")
        text=" ".join(answer+[step["sentence_frame"] for step in lp["write_sentence_steps"]])
        check(not BAN.search(text) and not CAN_BAD.search(text),f"GRAMMAR_BOUNDARY:{rid}")
        modes=[step["response_mode"] for step in lp["write_sentence_steps"][1:]]
        if entry["operation"]=="TABLE_TO_SENTENCES":
            blanks=ta["frame_blank_answers"]
            check(len(answer)==3 and len(blanks or [])==2
                  and modes==["FILL_ONE_WORD"]*2
                  and all(lp["write_sentence_steps"][j]["sentence_frame"]
                          .replace("______",blanks[j-1])==answer[j] for j in (1,2)),
                  f"TABLE_ANSWER_EXACTNESS:{rid}")
        elif entry["operation"]=="COPY_AND_CHANGE":
            check(len(answer)==2 and lp["original_model_sentence"] and lp["change_cue"]
                  and modes==["SUBSTITUTE_SUBJECT_AND_WRITE_FULL_SENTENCE"],
                  f"SUBSTITUTION_NOT_PERFORMED:{rid}")
        elif entry["operation"]=="SENTENCE_PLAN":
            check(len(answer)==3 and modes==["WRITE_FULL_SENTENCE_FROM_CUES"]*2,
                  f"FULL_SENTENCE_PLAN:{rid}")
        elif entry["operation"]=="GUIDED_MINI_TEXT":
            check(len(answer)==4 and modes==["WRITE_FULL_SENTENCE_FROM_CUES"]*3,
                  f"MINI_TEXT_LENGTH:{rid}")
    check(counts==mapping["writing_operation_counts"],"OPERATION_DISTRIBUTION_DRIFT")
    return {
        "status":"PASS_WRITING360_GPT6_BATCHES_PARTIAL_ADMISSION_GATE",
        "source_mapped":360,"operator_approved_pilot":15,
        "gpt6_authored_self_reviewed":len(authored),
        "pending_authoring":345-len(authored),
        "full360_admitted":False,"operation_distribution":counts,
        "batch_count":len(files)
    }

if __name__=="__main__":
    print(json.dumps(validate(),ensure_ascii=False,indent=2))
